name: flutter_rwtapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_bloc: ^2.1.1
  font_awesome_flutter: ^8.5.0
  flutter_pdfview: ^1.0.4
  path_provider: ^1.2.0
  image_picker: ^0.6.7+14
  provider:
  intl: ^0.16.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_pdfview: ^1.0.4
  adhara_socket_io: ^0.4.2+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/logos/backg.png
    - assets/logos/lock.png
    - assets/logos/login.png
    - assets/logos/user.png
    - assets/logos/logo.png


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf